#!/usr/bin/env bash

# Function to display usage
display_usage() {
    echo "Usage: $0 {IP_ADDRESS}"
}

# Check if argument is provided
if [ $# -eq 0 ]; then
    display_usage
    exit 1
fi

# Check if help flag is provided
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    display_usage
    exit 0
fi

# Ping the IP 5 times
ping -c 5 "$1"

