#!/usr/bin/env bash
#a Bash script that displays the content of the file /etc/passwd

passwd_file="/etc/passwd"

while IFS=: read -r username _ userid _ homedir _
do
	echo "username: $username"
	echo "user ID: $userid"
	echo "Home Directory: $homedir"
	echo
done < "$passwd_file"
