#!/usr/bin/env bash
#while loop and if statement to display "Best School" 10x
#print "hi" after 9th iteration

counter=1

while [ $counter -le 10 ]
do
	if [ $counter -eq 9 ]; then
	  echo "Best School"
	  echo "Hi"
	else
		echo "Best School"
	fi
	((counter++))
done
