#!/usr/bin/env bash
#while loop to display time for 12 hours and 59 minutes

hour=0

while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	if [ $hour -eq 0 ];then
		minute=1
	else
		minute=0
	fi

	while [ $minute -le 59 ]
	do
		echo "$minute"
		((minute++))
done
	((hour++))
done
