#!/usr/bin/env bash
# Check if the script is running in Docker

if [ -f /.dockerenv ]; then
    # Modify /etc/hosts to set localhost to 127.0.0.2 and facebook.com to 8.8.8.8
    echo "127.0.0.2 localhost" | tee -a /etc/hosts >/dev/null
    echo "8.8.8.8 facebook.com" | tee -a /etc/hosts >/dev/null
    echo "DNS configuration updated."
else
    echo "This script should be run inside a Docker container."
    exit 1
fi

