#!/usr/bin/env bash
# script to check if the script is running in Docker
if [ -f /.dockerenv ]; then
    # Check if localhost already resolves to 127.0.0.2, if not, update it
    if grep -qxF '127.0.0.2 localhost' /etc/hosts; then
        echo "localhost already resolves to 127.0.0.2"
    else
        echo "127.0.0.2 localhost" | tee -a /etc/hosts >/dev/null
        echo "Updated localhost to resolve to 127.0.0.2"
    fi

    # Check if facebook.com already resolves to 8.8.8.8, if not, update it
    if grep -qxF '8.8.8.8 facebook.com' /etc/hosts; then
        echo "facebook.com already resolves to 8.8.8.8"
    else
        echo "8.8.8.8 facebook.com" | tee -a /etc/hosts >/dev/null
        echo "Updated facebook.com to resolve to 8.8.8.8"
    fi
else
    echo "This script should be run inside a Docker container."
    exit 1
fi

